version: '3'

services:
  mysql:
    image: 'mysql'
    container_name: 'java-mysql'
    environment:
      - 'MYSQL_ROOT_USER=root'
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_DATABASE=jdbc'
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - '8080:8080'